#######################################
###### Variables for all hosts ########
#######################################

# SSH access key for all instances
ansible_ssh_private_key_file: "{{ lookup('env', 'OS_IMAGE_SSH_KEY') }}"
ansible_user: ubuntu