- name: Create kubernetes blockchain
  script: |
    create_k8s_blockchain.py {{ crpto_config_dir }} "{{ k8s_kubectl_cmd }}" {% if not fabric_create_cli %} --no-cli {% endif %}
    touch {{ crpto_config_dir }}/k8s_created
  args:
    executable: python3
    creates: "{{ crpto_config_dir }}/k8s_created"

- name: Sleeing 10 seconds for Fabric network to come-up
  pause:
    seconds: 10