- name: Create kubernetes blockchain
  script: >
    create_k8s_blockchain.py {{ crpto_config_dir }} "{{ k8s_kubectl_cmd }}"
    {% if not fabric_create_cli %}--no-cli{% endif %} {% if fabric_orderer_type == "kafka" %}--kafka{% endif %}
  args:
    executable: python3
    creates: "{{ crpto_config_dir }}/k8s_created"

- name: Mark kubernetes blockchain created
  file:
    path: "{{ crpto_config_dir }}/k8s_created"
    state: touch

- name: Sleeing "{{ fabric_boot_wait }}" seconds for Fabric network to come-up
  pause:
    seconds: "{{ fabric_boot_wait|int }}"
