---
- name: Unmount NFS from k8s worker nodes. To resolve kubectl delete hanging problem
  shell: |
    ssh {{ item }} -i ~/.ssh/i13.openstack.image.key.pem "sudo mount -t nfs4 | grep {{ nfs_server_ip }} | awk '/:/ { print $3 } ' | xargs sudo umount - l";
  with_items: "{{ groups['kube-node'] }}"
  ignore_errors: yes

- name: Delete kubernetes blockchain
  script: |
    delete_k8s_blockchain.py {{ crpto_config_dir }} "{{ k8s_kubectl_cmd }}"
  args:
    executable: python3
