---
test:
  clients:
    type: local
    number: 10

  rounds:
  - label: initLedger
    txNumber:
    - 1
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1
    callback: ../inventory/blockchain/benchmark/fabvar/initLedger.js

  - label: addToVar
    txNumber:
    - 1000
    - 1000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 100
    - type: fixed-rate
      opts:
        tps: 200
    callback: ../inventory/blockchain/benchmark/fabvar/addToVar.js

monitor:
  type:
  - process
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
