---
test:
  clients:
    type: local
    number: 5

  rounds:
  - label: moveVar
    txNumber:
    - 5000
    - 5000
    rateControl:
    - type: fixed-rate
      opts:
        tps: 100
    - type: fixed-rate
      opts:
        tps: 200
    callback: ../inventory/blockchain/benchmark/fabvar/moveVar.js

  - label: getSum
    txNumber:
    - 10
    rateControl:
    - type: fixed-rate
      opts:
        tps: 1
    callback: ../inventory/blockchain/benchmark/fabvar/getSum.js

monitor:
  type:
  - process
  process:
  - command: node
    arguments: local-client.js
    multiOutput: avg
  interval: 1
