---
- name: Remove crypto configs
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ nfs_server_mount_dir }}/{{ crypto_config_dirname }}"
    - "{{ crpto_config_dir }}"

- name: Remove channel artifacts
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ nfs_server_mount_dir }}/{{ channel_artifacts_dirname }}"
    - "{{ channel_artifacts_dir }}"

- name: Remove contract from NFS
  file:
    path: "{{ nfs_server_mount_dir }}/{{ contract_dirname }}"
    state: absent

- name: Remove kubernetes templates
  file:
    path: "{{ templates_dir }}"
    state: absent

- name: Remove fabric binaries
  file:
    path: "{{ fabric_config_dir }}/bin/"
    state: absent