---
- name: Create kubernetes templates directory
  file:
    path: "{{ templates_dir }}"
    state: directory

- name: Generate Kubernetes configuration templates
  template: src={{ item.src }} dest={{ templates_dir }}/{{ item.dest }} mode=0644
  with_items:
    - { src: "fabric_template_namespace.yaml.j2", dest: "fabric_template_namespace.yaml" }
    - { src: "fabric_template_pod_ca.yaml.j2", dest: "fabric_template_pod_ca.yaml" }
    - { src: "fabric_template_pod_cli.yaml.j2", dest: "fabric_template_pod_cli.yaml" }
    - { src: "fabric_template_pod_orderer.yaml.j2", dest: "fabric_template_pod_orderer.yaml" }
    - { src: "fabric_template_pod_peer.yaml.j2", dest: "fabric_template_pod_peer.yaml" }

- name: Generate kubernetes configuration
  script: |
    generate_k8s_configs.py {{ crpto_config_dir }} {{ templates_dir }}
  args:
    executable: python3

- name: Set owner and permission for kubernetes templates
  shell: |
    chown -R ubuntu:ubuntu {{ templates_dir }}
    chmod -R 777 {{ templates_dir }}
