---
- name: Generate Certs
  script: |
    bin_{{ fabric_version }}/cryptogen generate --config={{ cryptogen_config }} --output={{ crpto_config_dir }}

- name: Create channel artifacts dir
  file:
    name: "{{ channel_artifacts_dir }}"
    state: directory

- name: Generate channel artifacts
  script: >
    bin_{{ fabric_version }}/configtxgen -configPath {{ configtxgen_config_path }}  -profile TwoOrgsOrdererGenesis
    -outputBlock {{ channel_artifacts_dir }}/genesis.block -channelID orderer-system-channel

- name: Set permission for channel artifacts
  shell: |
    chmod -R 777 {{ channel_artifacts_dir }}

- name: Set permission for crypto configs
  shell: |
    chmod -R 777 {{ crpto_config_dir }}

- name: Copy genesis block to orderer
  shell: |
    cp {{ channel_artifacts_dir }}/genesis.block {{ crpto_config_dir }}/ordererOrganizations/

- name: Copy channel artifacts to NFS
  shell: |
    cp -r {{ channel_artifacts_dir }} {{ nfs_server_mount_dir }}

- name: Copy crypto configs to NFS
  shell: |
    cp -r {{ crpto_config_dir }} {{ nfs_server_mount_dir }}
