# Ansible Playbook to delete Hyperledger Fabric on kubernetes
# Note: Call with -i inventory/blockchain/hosts.ini
---
# Delete configurations
- hosts: blockchain-setup
  become: true
  roles:
    - { "role": network_config, delete: true }

# Prepare CLI node: Un-Mount NFS
- hosts: blockchain-setup
  become: true
  roles:
    - { "role": prepare_cli_node, "nfs_state": "absent" }
