# Ansible Playbook to delete Openstack Instances of Kubernetes cluster
# Note: Call with -i inventory/infra/hosts.ini
---
# Prepare CLI node: Un-mount NFS
- hosts: localhost
  become: true
  tasks:
    - name: Unmount /opt/share in CLI
      mount:
        path: /opt/share
        fstype: nfs4
        state: "absent"

# Delete Instances
- hosts: os-infra
  roles:
    - { "role": os_instance, "delete": true }
