# Ansible Playbook to install Hyperledger Fabric on kubernetes
# Note: Call with -i inventory/blockchain/hosts.ini
---
# Install Fabric Network.
- hosts: blockchain-setup
  roles:
    - { "role": network_setup, install: true }
