# Config Directories
fabric_config_dirname: fabric-configs
fabric_config_dir: "{{ inventory_dir }}/{{ fabric_config_dirname }}"
crypto_config_dirname: crypto-config
crpto_config_dir: "{{ fabric_config_dir }}/{{ crypto_config_dirname }}"
channel_artifacts_dirname: channel-artifacts
channel_artifacts_dir: "{{ fabric_config_dir }}/{{ channel_artifacts_dirname }}"

# Channel configuration
channel_name: mychannel

# Fabric Network Config
fabric_num_orgs: 2
fabric_peers_per_org: 2
fabric_num_orderer: 1
fabric_orderer_address: orderer0.orgorderer1
fabric_orderer_type: solo       # Options: solo/kafka
fabric_num_kafka: 3
fabric_num_zookeeper: 3
